name: manual_lkds
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  html: ^0.15.0
  webview_flutter: ^3.0.0
  webview_flutter_web: ^0.1.0+4
  flutter_pdfview: ^1.2.2
#  advance_pdf_viewer: ^2.0.1
  syncfusion_flutter_pdfviewer: ^20.3.47
  path_provider: ^2.0.4
  fluro: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/docs/